name = "TrimSimpleNonlinearSolve2"
uuid = "ce79173c-e404-40ce-8d4a-c0777d309ff8"
version = "0.0.1"
authors = ["Romeo Valentin (romeov@stanford.edu)"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
DiffEqBase = {path = "/home/romeo/.julia/dev/DiffEqBase"}
ForwardDiff = {path = "/home/romeo/.julia/dev/ForwardDiff"}
LinearSolve = {path = "/home/romeo/.julia/dev/LinearSolve"}
NonlinearSolveBase = {path = "/home/romeo/Documents/github/NonlinearSolve.jl/lib/NonlinearSolveBase/"}
Polyester = {path = "/home/romeo/.julia/dev/Polyester"}
PolyesterWeave = {path = "/home/romeo/.julia/dev/PolyesterWeave"}
SciMLBase = {path = "/home/romeo/.julia/dev/SciMLBase"}

[compat]
ADTypes = "1.15.0"
LinearSolve = "3.23.0"
NonlinearSolve = "4.10.0"
NonlinearSolveFirstOrder = "1.6.0"
SimpleNonlinearSolve = "2.7.0"
