name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '~1.12.0-rc1'
          arch: x64

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2

      - name: Build executable
        run: |
          make

      - name: Test executable
        run: |
          ./main 1.0